#!/bin/sh

# This script runs the two programs or takes the output
# and turns them into csv files, then it will also generate the combined csv file

ORDINARY_PROGRAM="OrdIsingStructure.jl"
ORDINARY_CSV_FILE="figure_edge_hist/ord_l25.csv"
PREFERENCE_PROGRAM="EvoIsingStructure.jl"
PREFERENCE_CSV_FILE="figure_edge_hist/evo_l25.csv"
BOTH_CSV_FILE="figure_edge_hist/l25.csv"

cd "$( dirname "${BASH_SOURCE[0]}" )"

function getCsvFromOutput {
	data=$(echo $1 | tr -d '[],' | awk '{for(i=1;i<=NF;i++){n=25-(i-1);printf "%d,%s\n",n,$i}}')
	echo "difference,edges"
	echo "$data"
}

function makeCombinedInput {
	awkCommand='{for(i=1;i<=NF;i++){n=25-(i-1)'$2'0.25;printf "%s,%s,'$3'\n",n,$i}}'
	data=$(echo $1 | tr -d '[],' | awk "$awkCommand")
	echo "$data"
}

# ORDINARY_OUTPUT=$(julia "./$ORDINARY_PROGRAM")
# echo "Completed $ORDINARY_PROGRAM"
# PREFERENCE_OUTPUT=$(julia "./$PREFERENCE_PROGRAM")
# echo "Completed $PREFERENCE_PROGRAM"

ORDINARY_OUTPUT="[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.00252, 0.03316, 0.24092, 0.7234]"
PREFERENCE_OUTPUT="[0.0, 0.0, 0.0, 2.0e-5, 0.00024, 0.00084, 0.00276, 0.00826, 0.01918, 0.03478, 0.05454, 0.07806, 0.09106, 0.09144, 0.08102, 0.06002, 0.03822, 0.02276, 0.01624, 0.01794, 0.03074, 0.05294, 0.07954, 0.09772, 0.08466, 0.03702]"

ORDINARY=$(getCsvFromOutput "$ORDINARY_OUTPUT")
PREFERENCE=$(getCsvFromOutput "$PREFERENCE_OUTPUT")

echo "$ORDINARY" > "$ORDINARY_CSV_FILE"
echo "$PREFERENCE" > "$PREFERENCE_CSV_FILE"

COMBINED_CSV="difference,edges,l"
COMBINED_CSV+=$'\n'
COMBINED_CSV+=$(makeCombinedInput "$ORDINARY_OUTPUT" "+" "1")
COMBINED_CSV+=$'\n'
COMBINED_CSV+=$(makeCombinedInput "$PREFERENCE_OUTPUT" "-" "8")
echo "$COMBINED_CSV" > "$BOTH_CSV_FILE"
